<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Questão 03</title>
</head>

<body>
    <script>
        const usuarios = [
            {
                nome: "João",
                idade: 25,
                email: "joao@email.com"
            },
            {
                nome: "Pedro",
                idade: 33,
                email: "pedro@email.com"
            },
            {
                nome: "Marcos",
                idade: 16,
                email: "marcos@email.com"
            }
        ];

        class UserNotFoundError extends Error {
            constructor(message) {
                super(message);
                this.name = "UserNotFoundError";
            }
        }

        function obtemUsuarioPeloNome(nome) {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    const user = usuarios.find(pessoa => pessoa.nome === nome);

                    if (!user) {
                        reject(new UserNotFoundError("Usuário não encontrado!"));
                    } else {
                        resolve(user);
                    }
                }, 3000);
            });
        }

        obtemUsuarioPeloNome("Marcos")
            .then(pessoa => console.log(`Usuário encontrado:\nnome: ${pessoa.nome}\nidade: ${pessoa.idade}\nemail: ${pessoa.email}.`))
            .catch(error => console.log(`Ocorreu um erro! ${error.message}`));
    </script>
</body>

</html>